name: DiT
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
#  - pytorch >= 1.13
  - torchvision
#  - pytorch-cuda=11.7
  - pip:
/mnt/pentagon/xiw136/local-refine-diffuser/pretrained_models    - timm
    - diffusers
    - accelerate
    - clean-fid
    - openpyxl
    - matplotlib
    - einops
    - pandas
    - tifffile
